### ISSUE TITLE
may any one help my the notification didn't work :" 

### ISSUE THREAD

**Issue by mohamedhussieen** [kreait/laravel-firebase#139] opened 2022-06-22 10:05 UTC

**Comment by jeromegamez** [comment] 2022-06-22 10:07
Sorry, but without a detailed description, I cannot help you. Please update the issue title and description with a reproducible scenario 🙏

**Comment by jeromegamez** [comment] 2022-06-22 10:09
Duplicate of #140

**Closed as completed by jeromegamez** 2022-06-22 10:09 UTC
