### ISSUE TITLE
Issue while installing this package on Laravel 8.40

### ISSUE THREAD

**Issue by rinkuanuragkumar** [kreait/laravel-firebase#142] opened 2022-07-06 09:12 UTC
**I'm unable to install on Laravel 8.40**
Kindly resolve my issue as soon as possible.
**Below are the error logs...**

```
composer require kreait/laravel-firebase

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.1 for kreait/laravel-firebase
./composer.json has been updated
Running composer update kreait/laravel-firebase
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - kreait/firebase-php 6.x-dev requires symfony/polyfill-php80 ^1.23 -> found symfony/polyfill-php80[dev-main, v1.23.0, ..., 1.26.x-dev (alias of dev-main)] but the package is fixed to v1.22.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/firebase-php[6.0.0, ..., 6.4.0] require guzzlehttp/guzzle ^7.4 -> found guzzlehttp/guzzle[dev-master, 7.4.0, ..., 7.4.x-dev (alias of dev-master)] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/firebase-php 6.4.1 requires guzzlehttp/guzzle ^7.4.4 -> found guzzlehttp/guzzle[dev-master, 7.4.4, 7.4.5, 7.4.x-dev (alias of dev-master)] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/firebase-php[6.5.0, ..., 6.5.1] require guzzlehttp/guzzle ^7.4.5 -> found guzzlehttp/guzzle[dev-master, 7.4.5, 7.4.x-dev (alias of dev-master)] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/laravel-firebase 4.1.0 requires kreait/firebase-php ^6.0 -> satisfiable by kreait/firebase-php[6.0.0, ..., 6.x-dev].
    - Root composer.json requires kreait/laravel-firebase ^4.1 -> satisfiable by kreait/laravel-firebase[4.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**When running with --with-all-dependencies (-W)
then results are...**

```
composer require kreait/laravel-firebase --with-all-dependencies

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.1 for kreait/laravel-firebase
./composer.json has been updated
Running composer update kreait/laravel-firebase --with-all-dependencies
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^8.12, found laravel/framework[v8.12.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - laravel/tinker is locked to version v2.6.1 and an update of this package was not requested.
    - laravel/tinker v2.6.1 requires illuminate/console ^6.0|^7.0|^8.0 -> found illuminate/console[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 3
    - laravel/ui is locked to version v3.2.1 and an update of this package was not requested.
    - laravel/ui v3.2.1 requires illuminate/console ^8.0 -> found illuminate/console[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 4
    - spatie/laravel-permission is locked to version 4.3.0 and an update of this package was not requested.
    - spatie/laravel-permission 4.3.0 requires illuminate/auth ^6.0|^7.0|^8.0 -> found illuminate/auth[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 5
    - tymon/jwt-auth is locked to version 1.0.2 and an update of this package was not requested.
    - tymon/jwt-auth 1.0.2 requires illuminate/auth ^5.2|^6|^7|^8 -> found illuminate/auth[v5.2.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 6
    - uxweb/sweet-alert is locked to version 2.0.5 and an update of this package was not requested.
    - uxweb/sweet-alert 2.0.5 requires illuminate/session ~5.0|^6.0|^7.0|^8.0 -> found illuminate/session[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 7
    - yajra/laravel-datatables-oracle is locked to version v9.19.0 and an update of this package was not requested.
    - yajra/laravel-datatables-oracle v9.19.0 requires illuminate/database 5.8.*|^6|^7|^8|^9 -> found illuminate/database[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 8
    - laravel/sail is locked to version v1.5.0 and an update of this package was not requested.
    - laravel/sail v1.5.0 requires illuminate/console ^8.0|^9.0 -> found illuminate/console[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 9
    - facade/flare-client-php 1.8.0 requires illuminate/pipeline ^5.5|^6.0|^7.0|^8.0 -> found illuminate/pipeline[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - facade/ignition 2.8.4 requires facade/flare-client-php ^1.6 -> satisfiable by facade/flare-client-php[1.8.0].
    - facade/ignition is locked to version 2.8.4 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by jeromegamez** [comment] 2022-07-06 09:38
Closing because this is not a bug in this package. Feel free to share if it works in further comments.

**Closed by jeromegamez** 2022-07-06 09:38 UTC
