### ISSUE TITLE
`signInWithFacebookAccessToken`'s result is returning null `firebaseUserId`

### ISSUE THREAD

**Issue by arifszn** [kreait/laravel-firebase#117] opened 2022-01-12 13:37 UTC
I have a user on firebase having email `x@gmail.com` and provider google. Now, when I use `signInWithFacebookAccessToken` with facebook account having the same mail, I am getting null `firebaseUserId`.

The rest of the information are correct and the uid is showing elsewhere in `data->localId`.

**Comment by jeromegamez** [comment] 2022-01-12 21:04
Unfortunately, you didn't share which version of the package and library you are using and no code that I can try to reproduce the problem with 😭, so I'll have to do a bit of guesswork here.

Can you confirm that the ID you expected is present in the `localId` property of the returned `SignInResult` object and the `firebaseUserId` is `null`?

If you're indeed talking about the properties, please note that you need to use the [`firebaseUserId()`](https://github.com/kreait/firebase-php/blob/bc575a115141065cef71ae3fb101495c9f725626/src/Firebase/Auth/SignInResult.php#L52) **method** to access the property.

Otherwise, please provide more information so that I can try to reproduce the problem.

**Comment by arifszn** [comment] 2022-01-13 06:23
@jeromegamez, Sorry I missed out on the information.

The code I am using:
```php
$signInResult = $this->auth->signInWithFacebookAccessToken($accessToken);
$firebaseUser = $this->auth->getUser($signInResult->firebaseUserId());
```

This is dumped `$signInResult`:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/45073703/149275505-2c3ae3cc-fef9-4d56-b32b-23ee8f70d027.png">

Yes, the `data->localId` has the same uid which is in the firebase console.
![image](https://user-images.githubusercontent.com/45073703/149276219-b7a66d16-cf15-47c6-b6b6-d1395d373946.png)


The version I am using:
```json
"name": "kreait/laravel-firebase",
"version": "3.2.0",
```

Laravel version: 
```json
"name": "laravel/framework",
"version": "v8.70.2",
```

PHP version: `8`

**Comment by jeromegamez** [comment] 2022-01-15 14:09
Thank you for providing the additional info 🙏. Unfortunately I can't fully reproduce the problem because I don't have a project available where I can test the federated login.

Could you please look into your Firebase Auth Users (at https://console.firebase.google.com/project/beste-firebase/authentication/users) and confirm that the `localId` from your response matches a user in your auth database?

So, as an example, if the value in the `localId` field in the response above was `sU2Wml0hAKPHDKKTr1trOEPLv4u2`, you should find the same ID by entering it in the search field of the auth users.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/67554/149624567-e20c6c12-95a5-4d7e-b8a2-d135a01e4d18.png">

If you can confirm this, I'll add this as a fallback to the `SignInResult` class, but can't promise it is correct 😅

**Comment by jeromegamez** [comment] 2022-01-15 14:22
Thank you for providing the additional info! I was able to confirm the issue and have added support for the `localId` field in https://github.com/kreait/firebase-php/commit/ff7c396cb143e298c72f1a19967c0986b4821cfd (5.x) and https://github.com/kreait/firebase-php/commit/35ec1919c6ed8d4f88134e4fd6953d9f044af836 (6.x), will create a new release shortly and notify you here.

**Comment by jeromegamez** [comment] 2022-01-16 12:02
Released with https://github.com/kreait/firebase-php/releases/tag/6.0.1 and https://github.com/kreait/firebase-php/releases/tag/5.26.1

Thanks again for raising the issue!

**Closed by jeromegamez** 2022-01-16 12:02 UTC
