### ISSUE TITLE
Kreait\Firebase\Exception\Database\ApiConnectionFailed

### ISSUE THREAD

**Issue by shouvick** [kreait/laravel-firebase#55] opened 2020-08-29 17:34 UTC
I am getting this error. previously it's working fine. I am using a firebase realtime database

Kreait\Firebase\Exception\Database\ApiConnectionFailed Unable to connect to the API: Connection refused for URI https://oauth2.googleapis.com/token

what is the possible problem?

**Comment by jeromegamez** [comment] 2020-08-29 19:05
Duplicate of https://github.com/kreait/firebase-php/issues/466

**Closed** 2020-08-29 19:05 UTC
